### ISSUE TITLE
[BUG] Private Island Broken On First Join

### ISSUE THREAD

**Issue by JustAiden9** [Swofty-Developments/HypixelSkyBlock#344] opened 2024-06-22 12:16 UTC
**Describe the bug**
When I join in I am able to see the minions and stone island, but I don't have the grass island. I checked to see if the template was corrupted, but it was not and worked as it should in singleplayer. I just fall into the void over and over. 

**To Reproduce**
1. Go on version '1.20.6'
2. Join
3. See the error

**Expected behavior**
Spawn on a grassy island not the void.

**Screenshots**
![Screenshot 2024-06-22 071830](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/104693998/83d50b8a-84aa-42e5-a93b-98e25db43175)

**Additional context**
Here is the Island Log File:
PS C:\Users\aiden\OneDrive\Desktop\Skyblock\SBServer> java --enable-preview -jar SkyBlockCore.jar ISLAND
2024-06-22 07:05:28 [main] net.swofty.loader.SkyBlock.lambda$main$1() INFO: Found TypeLoader: THE_FARMING_ISLANDS
2024-06-22 07:05:28 [main] net.swofty.loader.SkyBlock.lambda$main$1() INFO: Found TypeLoader: ISLAND
2024-06-22 07:05:30 [main] net.swofty.types.generic.SkyBlockGenericLoader.initialize() INFO: All songs have been found, starting song service for this instance.
2024-06-22 07:05:31 [main] net.swofty.type.island.TypeIslandLoader.onInitialize() INFO: TypeIslandLoader initialized!
2024-06-22 07:05:31 [main] net.swofty.loader.SkyBlock.main() INFO: Initializing proxy support...
2024-06-22 07:05:31 [Thread-2] net.minestom.server.ServerProcessImpl.start() INFO: Starting SkyBlock server.
2024-06-22 07:05:31 [Thread-2] net.minestom.server.ServerProcessImpl.start() INFO: SkyBlock server started successfully.
2024-06-22 07:05:31 [Thread-2] net.swofty.loader.SkyBlock.lambda$main$4() INFO: Started server on port 20000 in 3444ms
2024-06-22 07:05:31 [Thread-2] net.swofty.loader.SkyBlock.lambda$main$4() INFO: Server Type: ISLAND
2024-06-22 07:05:31 [Thread-2] net.swofty.loader.SkyBlock.lambda$main$4() INFO: Internal ID: 88c84795-f31a-4d46-aef1-6f5bd61a850f
2024-06-22 07:06:21 [Ms-worker-1] net.swofty.types.generic.SkyBlockGenericLoader.lambda$initialize$30() INFO: Received new player: JustAiden (f539d1d0-d861-45cf-8c16-a6400e6b84e1)
2024-06-22 07:06:22 [ForkJoinPool.commonPool-worker-19] net.swofty.types.generic.event.actions.player.data.ActionPlayerDataLoad.run() INFO: New player joined: JustAiden...
2024-06-22 07:06:22 [] net.swofty.types.generic.event.actions.player.data.ActionPlayerDataSpawn.run() INFO: Loading player data for JustAiden...
java.lang.NullPointerException: Unknown block minecraft:grass
        at java.base/java.util.Objects.requireNonNull(Objects.java:259)
        at net.minestom.server.instance.anvil.AnvilLoader.loadBlockPalette(AnvilLoader.java:248)
        at net.minestom.server.instance.anvil.AnvilLoader.loadSections(AnvilLoader.java:210)
        at net.minestom.server.instance.anvil.AnvilLoader.loadMCA(AnvilLoader.java:114)
        at net.minestom.server.instance.anvil.AnvilLoader.loadChunk(AnvilLoader.java:90)
        at net.hollowcube.polar.AnvilPolar.readAnvilChunks(AnvilPolar.java:120)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:93)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:46)
        at net.swofty.types.generic.user.SkyBlockIsland.lambda$getSharedInstance$3(SkyBlockIsland.java:101)
        at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Unknown block minecraft:grass
        at java.base/java.util.Objects.requireNonNull(Objects.java:259)
        at net.minestom.server.instance.anvil.AnvilLoader.loadBlockPalette(AnvilLoader.java:248)
        at net.minestom.server.instance.anvil.AnvilLoader.loadSections(AnvilLoader.java:210)
        at net.minestom.server.instance.anvil.AnvilLoader.loadMCA(AnvilLoader.java:114)
        at net.minestom.server.instance.anvil.AnvilLoader.loadChunk(AnvilLoader.java:90)
        at net.hollowcube.polar.AnvilPolar.readAnvilChunks(AnvilPolar.java:120)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:93)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:46)
        at net.swofty.types.generic.user.SkyBlockIsland.lambda$getSharedInstance$3(SkyBlockIsland.java:101)
        at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Unknown block minecraft:grass
        at java.base/java.util.Objects.requireNonNull(Objects.java:259)
        at net.minestom.server.instance.anvil.AnvilLoader.loadBlockPalette(AnvilLoader.java:248)
        at net.minestom.server.instance.anvil.AnvilLoader.loadSections(AnvilLoader.java:210)
        at net.minestom.server.instance.anvil.AnvilLoader.loadMCA(AnvilLoader.java:114)
        at net.minestom.server.instance.anvil.AnvilLoader.loadChunk(AnvilLoader.java:90)
        at net.hollowcube.polar.AnvilPolar.readAnvilChunks(AnvilPolar.java:120)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:93)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:46)
        at net.swofty.types.generic.user.SkyBlockIsland.lambda$getSharedInstance$3(SkyBlockIsland.java:101)
        at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Unknown block minecraft:grass
        at java.base/java.util.Objects.requireNonNull(Objects.java:259)
        at net.minestom.server.instance.anvil.AnvilLoader.loadBlockPalette(AnvilLoader.java:248)
        at net.minestom.server.instance.anvil.AnvilLoader.loadSections(AnvilLoader.java:210)
        at net.minestom.server.instance.anvil.AnvilLoader.loadMCA(AnvilLoader.java:114)
        at net.minestom.server.instance.anvil.AnvilLoader.loadChunk(AnvilLoader.java:90)
        at net.hollowcube.polar.AnvilPolar.readAnvilChunks(AnvilPolar.java:120)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:93)
        at net.hollowcube.polar.AnvilPolar.anvilToPolar(AnvilPolar.java:46)
        at net.swofty.types.generic.user.SkyBlockIsland.lambda$getSharedInstance$3(SkyBlockIsland.java:101)
        at java.base/java.lang.Thread.run(Thread.java:1583)
2024-06-22 07:06:25 [Ms-TickScheduler] net.swofty.types.generic.SkyBlockGenericLoader.lambda$initialize$7() ERROR: Server TPS is below 20! TPS: 11.73604232486304
com.fasterxml.jackson.databind.JsonMappingException: Item is not a pet (through reference chain: net.swofty.types.generic.user.SkyBlockInventory["items"]->java.util.HashMap["8"]->net.swofty.types.generic.item.SkyBlockItem["attributeHandler"]->net.swofty.types.generic.item.ItemAttributeHandler["petData"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:778)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:183)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4799)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4040)
        at net.swofty.commons.protocol.serializers.InventorySerializer.serialize(InventorySerializer.java:27)
        at net.swofty.types.generic.data.Datapoint.getSerializedValue(Datapoint.java:59)
        at net.swofty.types.generic.data.DataHandler.lambda$toDocument$1(DataHandler.java:124)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at net.swofty.types.generic.data.DataHandler.toDocument(DataHandler.java:122)
        at net.swofty.types.generic.event.actions.player.data.ActionPlayerDataSave.run(ActionPlayerDataSave.java:52)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at net.swofty.types.generic.event.SkyBlockEventHandler.lambda$runEvent$6(SkyBlockEventHandler.java:147)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: java.lang.RuntimeException: Item is not a pet
        at net.swofty.types.generic.item.ItemAttributeHandler.getPetData(ItemAttributeHandler.java:87)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
        ... 26 more
2024-06-22 07:08:28 [Ms-TickScheduler] net.swofty.loader.SkyBlock.lambda$checkProxyConnected$10() ERROR: Proxy did not respond to alive check. Shutting down...
2024-06-22 07:08:28 [Thread-4] net.minestom.server.ServerProcessImpl.stop() INFO: Stopping SkyBlock server.
2024-06-22 07:08:28 [Thread-4] net.minestom.server.ServerProcessImpl.stop() INFO: Shutting down all thread pools.
2024-06-22 07:08:28 [Thread-4] net.minestom.server.ServerProcessImpl.stop() INFO: SkyBlock server stopped successfully.

**Comment by JustAiden9** [comment] 2024-06-22 13:18
A lot of my issues seem to be from [Ms-TickScheduler] did I not install something correctly?

**Comment by JustAiden9** [comment] 2024-06-22 13:23
Ok, something is definitely broken on my end I cant seem to get it to work.

**Comment by JustAiden9** [comment] 2024-06-22 13:30
Memurai did not install and will not install for me for some reason I am on windows 11 that may be why.

**Comment by Swofty-Developments** [comment] 2024-06-22 13:35
The issue is probably something to do with me, I'll have a look into it in a couple days

**Comment by JustAiden9** [comment] 2024-06-22 13:43
I was able to get Memurai installed, but still no luke for me.

**Comment by JustAiden9** [comment] 2024-06-22 13:43
Is there a way to use an older version of the core or something?

**Comment by Swofty-Developments** [comment] 2024-06-22 13:53
It would be possible to fork and manually rollback it and build. I believe when I migrated to 1.20.6 I didn't properly account for how islands should load in the new version for players without data.

**Comment by JustAiden9** [comment] 2024-06-22 13:59
Ah ok, so it is not a bug on my end most likely then?

**Comment by Swofty-Developments** [comment] 2024-06-22 14:04
Correct

**Comment by JustAiden9** [comment] 2024-06-22 18:03
I run the "java --enable-preview -jar SkyBlockCore.jar ISLAND" with --enable-preview is that a problem, if I don't it just does not want to start.

**Comment by JustAiden9** [comment] 2024-06-22 21:09
Ok it has to be a error on my end because I can't do anything on the island except open the skyblock menu. I can't use the crafting table (SB GUI), and some of the skills and collections all ready are at 12. I thought I installed everything, but maybe there is conflicts or something. Also the time and the TPS in tab is randomized and changing every time I die/fall into the void.

**Comment by JustAiden9** [comment] 2024-06-22 21:45
I also think it may be on my end because Vialoader or via version is broken for me.

**Comment by JustAiden9** [comment] 2024-06-22 22:00
Here is a screen recording that I made showing the errors. 
https://youtu.be/HK_sio_ayIA

**Comment by JustAiden9** [comment] 2024-06-22 22:31
Nvm did a bit of reading on the discord and found out that a ton of people have the same issue as me.

**Comment by khastaway** [comment] 2024-06-23 02:48
Could it possibly be an issue with the client being used? for example lunar client would work differently from vanilla?

**Comment by Swofty-Developments** [comment] 2024-06-23 02:54
I've fixed the issue but I've also tried migrating to 1.21 and it has been difficult

**Comment by Swofty-Developments** [comment] 2024-06-23 03:30
Fixed in the latest PRs

**Closed by Swofty-Developments** 2024-06-23 03:30 UTC
